# -*- coding: utf-8 -*-
"""Decision_Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10EZHG8VIVOuJjiySjeR-HhuqX99LFKLn
"""

# data gathering
import numpy as np
import pandas as pd
data = pd.read_csv('/content/BankNoteAuthentication.csv')
data.head()

# Divide the data
x = data.drop(['class'],axis=1)
y = data['class']
x.head()

y.head()

# split the data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

"""# Decision Tree Classification SNL Algorithum"""

from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()

tree.fit(x_train,y_train)

tree_predictions = tree.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,tree_predictions)
ac = accuracy_score(y_test,tree_predictions)

print(cm)

print(ac)