# -*- coding: utf-8 -*-
"""K-Nearest Neighbors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7px0s8wnpTGOcydDvenSXi87su-he0U

Step1 : gathering the data
"""

import numpy as np
import pandas as pd
data = pd.read_csv('/content/Social_Network_Ads.csv')
data.head()

"""Step2: Data cleaning"""

df = data.drop('User ID',axis=1)
df['Gender'] = df['Gender'].apply({'Male':0,'Female':1}.get)
df.head()

"""Step3: Divide the data"""

x = df.drop('Purchased',axis=1)
y = df['Purchased']
x.head()

y.head()

"""Step4: Split the data"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

"""# Creating the ML model for k-Nearest Neighbors algorithum"""

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
predictions = knn.predict(x_test)
print(predictions)

"""creating confusion matrix and accuracy """

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,predictions)
ac = accuracy_score(y_test,predictions)
print(cm)

print(ac)