# -*- coding: utf-8 -*-
"""Linear_Regression(Housing).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/139hogt7DbalL_OVOvRwi1Px1SbFUljZl

Step 1 : Gathering the data
"""

import numpy as np
import pandas as pd
data = pd.read_csv('/content/Housing.csv')
data.head()

"""Step2 : Data Cleaning"""

data['mainroad'] = data['mainroad'].apply({'no':0,'yes':1}.get)
data['guestroom'] = data['guestroom'].apply({'no':0,'yes':1}.get)
data['basement'] = data['basement'].apply({'no':0,'yes':1}.get)
data['hotwaterheating'] = data['hotwaterheating'].apply({'no':0,'yes':1}.get)
data['airconditioning'] = data['airconditioning'].apply({'no':0,'yes':1}.get)
data['prefarea'] = data['prefarea'].apply({'no':0,'yes':1}.get)
data['furnishingstatus'] = data['furnishingstatus'].apply({'furnished':1,'semi-furnished':2,'unfurnished':3}.get)
data.head()

"""Stem3 : Divide the data into independant(x) dependant(y) variables"""

x = data[['area','bedrooms','bathrooms','stories','mainroad','guestroom','basement','hotwaterheating','airconditioning','parking','prefarea','furnishingstatus']]
y = data['price']
x.head()

y.head()

"""Step4 : Split the data into training and testing """

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

x_train.shape

x_test.shape

"""Creating machine learning model for linear regression algorithum"""

from sklearn.linear_model import LinearRegression
regression = LinearRegression()

regression.fit(x_train,y_train)

predictions = regression.predict(x_test)
print(predictions.size)
print(predictions)

regression.score(x,y)

"""Predictions for new data set"""

new = {'area':8000,'bedrooms':3,'bathrooms':4,'stories':2,'mainroad':1,'guestroom':1,'basement':1,'hotwaterheating':1,'airconditioning':1,'parking':3,'prefarea':1,'furnishingstatus':1}
index = [1]
newdata = pd.DataFrame(new,index)
print(newdata)