# -*- coding: utf-8 -*-
"""Logistic_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ewv7o_qTscCYRfqU6sMYp7xsA_EywPPN

Step1: Gathering the Data
"""

import numpy as np 
import pandas as pd
data = pd.read_csv('/content/insurance2.csv')
data.head()

"""Step2: Data Cleaning

Step3:Dividing the data into independant and dependant variables
"""

x = data.drop(['insuranceclaim'],axis=1)
y = data['insuranceclaim']
x.head()

y.head()

"""Step4: Split the data for treaning and testing"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

"""# Creating the ML model for Logistic regression"""

from sklearn.linear_model import LogisticRegression
logRegression = LogisticRegression()

logRegression.fit(x_train, y_train)

predictions = logRegression.predict(x_test)
print(predictions)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,predictions)
ac = accuracy_score(y_test,predictions)

print(cm)

print(ac)