# -*- coding: utf-8 -*-
"""Random_Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yrpwAgdQM51gFIwSwjwnha2d9U-cfplE
"""

# data gathering
import numpy as np
import pandas as pd
data = pd.read_csv('/content/BankNoteAuthentication.csv')
data.head()

# Divide the data
x = data.drop(['class'],axis=1)
y = data['class']
x.head()

y.head()

# split the data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

"""# Random Forest Classification SNL Algorithum"""

from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier()

forest.fit(x_train,y_train)

forest_predictions = forest.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,forest_predictions)
ac = accuracy_score(y_test,forest_predictions)

print(cm)

print(ac)